"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var jsx_runtime_1 = require("react/jsx-runtime");
var label_1 = require("@/components/ui/label");
var card_1 = require("@/components/ui/card");
var switch_1 = require("@/components/ui/switch");
var PosterSettings = function (_a) {
    var theme = _a.theme, setTheme = _a.setTheme, language = _a.language, setLanguage = _a.setLanguage, zoom = _a.zoom, setZoom = _a.setZoom;
    return ((0, jsx_runtime_1.jsxs)("div", { className: "form-settings space-y-4", children: [(0, jsx_runtime_1.jsx)(label_1.Label, { className: "text-lg font-semibold", children: "\u0411\u0440\u0437\u0430 \u043F\u043E\u0434\u0435\u0448\u0430\u0432\u0430\u045A\u0430" }), (0, jsx_runtime_1.jsxs)("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-4", children: [(0, jsx_runtime_1.jsx)(card_1.Card, { className: "p-4 transition-all hover:shadow-md", children: (0, jsx_runtime_1.jsxs)("div", { className: "flex flex-col items-center gap-3 h-full", children: [(0, jsx_runtime_1.jsx)(label_1.Label, { className: "text-sm font-medium mb-2", children: "\u0422\u0435\u043C\u0435" }), (0, jsx_runtime_1.jsx)(switch_1.Switch, { checked: theme === "dark", onCheckedChange: function (checked) { return setTheme(checked ? 'dark' : 'light'); }, className: "scale-110" }), (0, jsx_runtime_1.jsx)("span", { className: "text-sm text-muted-foreground", children: theme === 'dark' ? 'Тамна' : 'Светла' })] }) }), (0, jsx_runtime_1.jsx)(card_1.Card, { className: "p-4 transition-all hover:shadow-md", children: (0, jsx_runtime_1.jsxs)("div", { className: "flex flex-col items-center gap-3 h-full", children: [(0, jsx_runtime_1.jsx)(label_1.Label, { className: "text-sm font-medium mb-2", children: "\u0408\u0435\u0437\u0438\u043A" }), (0, jsx_runtime_1.jsx)(switch_1.Switch, { checked: language === "srb", onCheckedChange: function (checked) { return setLanguage(checked ? 'srb' : 'eng'); }, className: "scale-110" }), (0, jsx_runtime_1.jsx)("span", { className: "text-sm text-muted-foreground", children: language === 'srb' ? 'Српски' : 'Енглески' })] }) }), (0, jsx_runtime_1.jsx)(card_1.Card, { className: "p-4 transition-all hover:shadow-md", children: (0, jsx_runtime_1.jsxs)("div", { className: "flex flex-col items-center gap-3 h-full", children: [(0, jsx_runtime_1.jsx)(label_1.Label, { className: "text-sm font-medium mb-2", children: "\u0417\u0443\u043C" }), (0, jsx_runtime_1.jsx)(switch_1.Switch, { checked: zoom, onCheckedChange: setZoom, className: "scale-110" }), (0, jsx_runtime_1.jsx)("span", { className: "text-sm text-muted-foreground", children: zoom ? 'Укључен' : 'Искључен' })] }) })] })] }));
};
exports.default = PosterSettings;
